# Advanced Programme in Deep Learning (Foundations and Applications)
## A Program by IISc and TalentSprint
### Assignment 2: Linear Algebra

## Learning Objectives

At the end of the assignment, you will be able to
* understand matrix, types of matrix, vectors and its related operations



### Setup Steps:

In [1]:
#@title Please enter your registration id to start: { run: "auto", display-mode: "form" }
Id = "2418729" #@param {type:"string"}

In [2]:
#@title Please enter your password (normally your phone number) to continue: { run: "auto", display-mode: "form" }
password = "81548026" #@param {type:"string"}

In [3]:
#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython
import warnings
warnings.filterwarnings("ignore")

ipython = get_ipython()

notebook= "M1_AST_01_Linear_Algebra_B" #name of the notebook

def setup():
    from IPython.display import HTML, display
    display(HTML('<script src="https://dashboard.talentsprint.com/aiml/record_ip.html?traineeId={0}&recordId={1}"></script>'.format(getId(),submission_id)))
    print("Setup completed successfully")
    return

def submit_notebook():
    ipython.magic("notebook -e "+ notebook + ".ipynb")

    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword()}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:
        print(r["err"])
        return None
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None

    elif getAnswer1() and getAnswer2() and getComplexity() and getAdditional() and getConcepts() and getComments() and getMentorSupport():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional,
              "concepts" : Concepts, "record_id" : submission_id,
              "answer1" : Answer1, "answer2" : Answer2, "id" : Id, "file_hash" : file_hash,
              "notebook" : notebook,
              "feedback_experiments_input" : Comments,
              "feedback_mentor_support": Mentor_support}
      r = requests.post(url, data = data)
      r = json.loads(r.text)
      if "err" in r:
        print(r["err"])
        return None
      else:
        print("Your submission is successful.")
        print("Ref Id:", submission_id)
        print("Date of submission: ", r["date"])
        print("Time of submission: ", r["time"])
        print("View your submissions: https://learn-iisc.talentsprint.com/notebook_submissions")
        #print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
        return submission_id
    else: submission_id


def getAdditional():
  try:
    if not Additional:
      raise NameError
    else:
      return Additional
  except NameError:
    print ("Please answer Additional Question")
    return None

def getComplexity():
  try:
    if not Complexity:
      raise NameError
    else:
      return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None

def getConcepts():
  try:
    if not Concepts:
      raise NameError
    else:
      return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None


# def getWalkthrough():
#   try:
#     if not Walkthrough:
#       raise NameError
#     else:
#       return Walkthrough
#   except NameError:
#     print ("Please answer Walkthrough Question")
#     return None

def getComments():
  try:
    if not Comments:
      raise NameError
    else:
      return Comments
  except NameError:
    print ("Please answer Comments Question")
    return None


def getMentorSupport():
  try:
    if not Mentor_support:
      raise NameError
    else:
      return Mentor_support
  except NameError:
    print ("Please answer Mentor support Question")
    return None

def getAnswer1():
  try:
    if not Answer1:
      raise NameError
    else:
      return Answer1
  except NameError:
    print ("Please answer Question 1")
    return None

def getAnswer2():
  try:
    if not Answer2:
      raise NameError
    else:
      return Answer2
  except NameError:
    print ("Please answer Question 2")
    return None


def getId():
  try:
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup()
else:
  print ("Please complete Id and Password cells before running setup")



Setup completed successfully


### Importing required packages

In [4]:
import numpy as np
from math import *
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from numpy import linalg as la
from numpy.linalg import eig

### Types of Matrix

**Square Matrix**: In square matrix, the number of rows are equal to the number of columns.

1. Create a square matrix with elements 61 to 69.

In [5]:
square_matrix = np.array([np.arange(61,64),np.arange(64,67), np.arange(67,70)])
print("Square Matrix:\n",square_matrix)

Square Matrix:
 [[61 62 63]
 [64 65 66]
 [67 68 69]]



**Upper Triangular Matrix**: It is a type of square matrix, where all the values below the main diagonal are 0.

**Lower Triangular Matrix**: It is a type of square matrix, where all the values above the main diagonal are 0.


2. Create an upper and lower triangular matrix of size 6x6 with random values.

In [6]:
matrix = np.random.rand(6,6)
print("Original Matrix:\n",matrix)

# Upper triangular matrix
# YOUR CODE HERE

upperTriangularMatrix = np.triu(matrix)
print(upperTriangularMatrix)

# Lower triangular matrix
# YOUR CODE HERE
lowerTriangularMatrix = np.tril(matrix)
print(lowerTriangularMatrix)

Original Matrix:
 [[4.05428676e-01 2.36381115e-01 9.97915338e-01 1.46864833e-01
  8.33442178e-01 3.50245401e-02]
 [6.83242226e-01 2.19789982e-01 5.79696575e-01 8.79764952e-02
  4.72226155e-01 1.81439594e-01]
 [9.66938597e-02 8.62583750e-01 5.48096384e-01 4.35439270e-01
  6.89473181e-01 5.73254923e-01]
 [4.87019004e-01 8.17013465e-01 9.77874955e-01 5.50678459e-01
  3.82954064e-01 7.20088089e-01]
 [8.05281143e-01 4.13059441e-01 2.14267830e-01 5.81351309e-02
  6.72523019e-01 2.42527115e-01]
 [1.66216118e-01 8.06880484e-01 9.76469940e-01 7.97793679e-01
  6.09649810e-01 6.80464456e-04]]
[[4.05428676e-01 2.36381115e-01 9.97915338e-01 1.46864833e-01
  8.33442178e-01 3.50245401e-02]
 [0.00000000e+00 2.19789982e-01 5.79696575e-01 8.79764952e-02
  4.72226155e-01 1.81439594e-01]
 [0.00000000e+00 0.00000000e+00 5.48096384e-01 4.35439270e-01
  6.89473181e-01 5.73254923e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 5.50678459e-01
  3.82954064e-01 7.20088089e-01]
 [0.00000000e+00 0.00000000e+00

**Diagonal Matrix**: In a diagonal matrix, all the values are zero except the diagonal values

3. Create a diagonal matrix of size 3x3 with integer valules and do the following:

  i). Create a diagonal matrix with the values above the diagonal elements.
  
  ii). Create a diagonal matrix with the values below the diagonal elements.





In [7]:
M = np.array([np.arange(73,76),np.arange(32,35), np.arange(57,60)])
print("Matrix:\n",M)

# Diagonal Matrix
diagonal_matrix = np.diag(np.diag(M))

# Using k=1 for getting the diagonal matrix with the values above the diagonal elements
above_matrix = np.diag(np.diag(M,k=1))

# Using k=-1 for getting the diagonal matrix with the values below the diagonal elements
below_matrix = np.diag(np.diag(M,k=-1))

print("Diagonal Matrix:\n",diagonal_matrix)
print("Matrix Above Diagonal:\n",above_matrix)
print("Matrix Below Diagonal:\n",below_matrix)

Matrix:
 [[73 74 75]
 [32 33 34]
 [57 58 59]]
Diagonal Matrix:
 [[73  0  0]
 [ 0 33  0]
 [ 0  0 59]]
Matrix Above Diagonal:
 [[74  0]
 [ 0 34]]
Matrix Below Diagonal:
 [[32  0]
 [ 0 58]]


Here all the non-diagonal elements are zero.

**Identity Matrix**: A matrix of size nxn where all diagonal values are 1 and other values are 0 is an identity matrix.

4. Create a 4x4 identity matrix with integer numbers.

In [8]:
# YOUR CODE HERE
squareMatrix = np.random.randint(1, 17, size=(4, 4))

diagonalElements = np.diag(squareMatrix) # creates a diagonal elements from the given square matrix
print(diagonalElements)

diagonalMatrix = np.diag(diagonalElements) # creates a diagonal matrix swith given linear elements
print(diagonalMatrix)


[6 1 2 7]
[[6 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 7]]


**Null Matrix**: A null matrix has all the values as zero.

5. Create a null matrix of integers with shape 6x6.

In [9]:
# YOUR CODE HERE
nullMatrix = np.zeros((6,6), dtype= int)
print(nullMatrix)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


### Matrix Transpose, Inverse, and Determinant

**Transpose**: Transpose operation flips the matrix over its diagonal i.e. replacing rows with coloums and vice-versa.

1. Create a matrix and find its transpose.

In [10]:
# Creating a matrix
matrix1 = np.array([np.arange(0,3),np.arange(3,6)])
print("Matrix 1:\n", matrix1)

# Matrix transpose
# YOUR CODE HERE

transposeMatrix = np.transpose(matrix1)
print(transposeMatrix)

Matrix 1:
 [[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


**Inverse**: This operation helps to create a matrix such that when it is multiplied by the original matrix, the result is an identity matrix.

2. Find the inverse of a matrix.

In [11]:
# Create a matrix
A = np.array([[5,6],[7,8]])

# Finding the inverse
# YOUR CODE HERE

determinent = np.linalg.det(A) # get the determinent of the matrix

if determinent != 0:
   inverseMatrix = np.linalg.inv(A)
   print(inverseMatrix)
else:
   print("Determinent is zero")

[[-4.   3. ]
 [ 3.5 -2.5]]


3. Create 3x3 matrix and find the inverse of it.

In [12]:
B = np.array([[1,9,3],[4,5,6],[7,8,9]])
print("Matrix B:\n", B)

# Finding Inverse
# YOUR CODE HERE

determinent = np.linalg.det(squareMatrix) # get the determinent of the matrix

if determinent != 0:
   inverseMatrix = np.linalg.inv(squareMatrix)
   print(inverseMatrix)
else:
   print("Determinent is zero")

Matrix B:
 [[1 9 3]
 [4 5 6]
 [7 8 9]]
[[-0.05125    -0.0125     -0.01208333  0.09541667]
 [ 0.09       -0.1         0.07       -0.07      ]
 [ 0.24125    -0.0875     -0.11791667  0.03458333]
 [-0.085       0.15        0.045      -0.045     ]]


**Determinant**: Determinant of a matrix is a scalar value that helps to characterize the properties of a matrix.

4. Create a matrix of size 3x3 and find the determinant of it.

  To know more about Python libraries, click [here](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html)




In [13]:
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = la.det(B)
print(D)

0.0


5. Create a 4x4 matrix and slice the rows and columns to get the middle sub-matrix and find its determinant.

In [14]:
# Create 4x4 matrix
matrix_new = np.array([np.arange(0,4),np.arange(4,8),np.arange(8,12),np.arange(12,16)])
print("Matrix:\n", matrix_new)

# Slicing of rows and columns
# YOUR CODE HERE

middleSubMatrix = squareMatrix[1:3, 1:3]
print(middleSubMatrix)

# Finding the determinant
# YOUR CODE HERE

determinant = np.linalg.det(middleSubMatrix)
print(determinant)

Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  4]
 [13  2]]
-50.000000000000014



### Matrix Operations and Functions


### Addition

1. Create matrix and add a scalar to it.





In [15]:
matrix1 = np.array([np.arange(27,32),np.arange(53,58),np.arange(33,38),np.arange(91,96)])
print("Original Matrix:\n",matrix1)

# Scalar Addition
# YOUR CODE HERE

scalar = 5

scalarAddition = matrix1 + scalar
print(scalarAddition)

Original Matrix:
 [[27 28 29 30 31]
 [53 54 55 56 57]
 [33 34 35 36 37]
 [91 92 93 94 95]]
[[ 32  33  34  35  36]
 [ 58  59  60  61  62]
 [ 38  39  40  41  42]
 [ 96  97  98  99 100]]


2. Create two matrices as matrix1 & matrix2. Then, perform addition operation on them.










In [16]:
# Creating matrices
matrix1 = np.array([np.arange(7,10),np.arange(24,27)])
matrix2 = np.array([np.arange(16,19),np.arange(33,36)])
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Matrix Addition
Matrix_addition = matrix1 + matrix2
print("Matrix Addition: \n",Matrix_addition)

Matrix 1:
 [[ 7  8  9]
 [24 25 26]]
Matrix 2:
 [[16 17 18]
 [33 34 35]]
Matrix Addition: 
 [[23 25 27]
 [57 59 61]]


### Subtraction

3. Create a matrix of size 3x6 and subtract a scalar from it.



In [17]:
# Creating matrices
matrix1 = np.array([np.arange(5,11), np.arange(47,53), np.arange(9,15)])
print("Matrix 1:\n", matrix1)

# Scalar Substraction
# YOUR CODE HERE

scalar = 5
substractionMatrix = matrix1 - scalar
print(substractionMatrix)

Matrix 1:
 [[ 5  6  7  8  9 10]
 [47 48 49 50 51 52]
 [ 9 10 11 12 13 14]]
[[ 0  1  2  3  4  5]
 [42 43 44 45 46 47]
 [ 4  5  6  7  8  9]]


4. Create two matrices of size 2x3 and subtract second matrix from the first one.

In [ ]:
# Creating matrices
matrix1 = np.array([np.arange(0,3),np.arange(3,6)])
matrix2 = np.array([np.arange(6,9),np.arange(9,12)])
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Matrix Subtraction
Matrix_subtraction = matrix1 - matrix2
print(Matrix_subtraction)

### Division

5. Create a 4x3 matrix and divide it by a scalar.






In [18]:
matrix1 = np.array([np.arange(6,9),np.arange(14,17),np.arange(97,100),np.arange(54,57)])
print("Matrix 1:\n", matrix1)

# Scalar Division
# YOUR CODE HERE

scalar = 5

divisionMatrix = matrix1 / 5
print(divisionMatrix)

Matrix 1:
 [[ 6  7  8]
 [14 15 16]
 [97 98 99]
 [54 55 56]]
[[ 1.2  1.4  1.6]
 [ 2.8  3.   3.2]
 [19.4 19.6 19.8]
 [10.8 11.  11.2]]


6. Create two matrices and divide the first matrix by the second one.

In [19]:
# Creating matrices
matrix1 = np.array([np.arange(18,21),np.arange(32,35)])
matrix2 = np.array([np.arange(6,9),np.arange(9,12)])
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Matrix Division
Matrix_div = matrix1/matrix2
print(Matrix_div)

Matrix 1:
 [[18 19 20]
 [32 33 34]]
Matrix 2:
 [[ 6  7  8]
 [ 9 10 11]]
[[3.         2.71428571 2.5       ]
 [3.55555556 3.3        3.09090909]]


### Multiplication

7. Create a matrix and mulitply it by a Scalar.




In [21]:
matrix1 = np.array([np.arange(121,126),np.arange(75,80)])
print("Matrix 1:\n", matrix1)

# Scalar Product
# YOUR CODE HERE
scalar = 5

scalarMultiply = matrix1 * 5
print("scalarMultiply 1:\n", scalarMultiply)

Matrix 1:
 [[121 122 123 124 125]
 [ 75  76  77  78  79]]
scalarMultiply 1:
 [[605 610 615 620 625]
 [375 380 385 390 395]]


Multiplication of two matrices is shown in the below diagram:



$A.B = \begin{bmatrix}
a & b\\
c & d\\
\end{bmatrix} \begin{bmatrix}
e & f\\
g & h\\
\end{bmatrix} = \begin{bmatrix}
ae+ bg & af+bh\\
ce+dg & cf+dh\\
\end{bmatrix}$

8. Create two matrices and multiply them.

  Note: Here, the corresponding elements are not multiplied. The multiplication rules are different from addition, subtraction, and division.

In [22]:
# Creating matrices
matrix1 = np.array([np.arange(5,9),np.arange(2,6)])
matrix2 = np.array([np.arange(6,8),np.arange(12,14),np.arange(4,6),np.arange(1,3)])
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Dot Product
Dot_product = np.dot(matrix1, matrix2)
print("Dot Product: \n",Dot_product)

Matrix 1:
 [[5 6 7 8]
 [2 3 4 5]]
Matrix 2:
 [[ 6  7]
 [12 13]
 [ 4  5]
 [ 1  2]]
Dot Product: 
 [[138 164]
 [ 69  83]]


### Please answer the questions below to complete the experiment:




Consider the statements given below and answer Q1.


A. Every skew-symmetric matrix of odd order is non-singular

B. If determinant of a square matrix is non-zero, then it is non singular

C. Adjoint of symmetric matrix is symmetric

D. Adjoint of a diagonal matrix is diagonal

In [23]:
#@title Q.1. Which of the above statements is/are False?
Answer1 = "Only A" #@param ["","Only A","Both A & B","Only B", "Only C", "Only D", "Both B & C"]


Consider the matrix A and the values of a, b, and c given below for answering Q.2.

$A = \begin{bmatrix}
0 & 2b & c   \\
a & b & -c   \\
a & -b & c   \\
\end{bmatrix}$

<br>

A). a = $\pm \frac{1}{\sqrt{6}} $, b = $\pm \frac{1}{\sqrt{2}}$ , c = $\pm \frac{1}{\sqrt{2}} $


<br>

B). a = $\pm \frac{1}{\sqrt{6}} $, b = $\pm \frac{1}{\sqrt{3}}$ , c = $\pm \frac{1}{\sqrt{2}} $


<br>

C). a = $\pm \frac{1}{\sqrt{2}} $, b = $\pm \frac{1}{\sqrt{6}}$ , c = $\pm \frac{1}{\sqrt{3}} $

<br>

D). a = $\pm \frac{1}{\sqrt{2}} $, b = $\pm \frac{1}{\sqrt{2}}$ , c = $\pm \frac{1}{\sqrt{2}} $

In [24]:
#@title Q.2. If 'A' is an orthogonal matrix, then, what will be the values of a, b, and c.
Answer2 = "Only A" #@param ["","Only A","Only B","Only C","Only D", "None of the above"]


In [26]:
#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = "Good, But Not Challenging for me" #@param ["","Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging for me", "Was Tough, but I did it", "Too Difficult for me"]


In [25]:
#@title If it was too easy, what more would you have liked to be added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = "Can add more complex code questions" #@param {type:"string"}


In [27]:
#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = "Yes" #@param ["","Yes", "No"]


In [28]:
#@title  Text and image description/explanation and code comments within the experiment: { run: "auto", vertical-output: true, display-mode: "form" }
Comments = "Very Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [29]:
#@title Mentor Support: { run: "auto", vertical-output: true, display-mode: "form" }
Mentor_support = "Very Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [30]:
#@title Run this cell to submit your notebook for grading { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id = return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")

Your submission is successful.
Ref Id: 133
Date of submission:  06 Dec 2024
Time of submission:  15:23:34
View your submissions: https://learn-iisc.talentsprint.com/notebook_submissions
