# Advanced Programme in Deep Learning (Foundations and Applications)
## A Program by IISc and TalentSprint
### Assignment 2: Linear Algebra

## Learning Objectives

At the end of the assignment, you will be able to
* understand matrix, types of matrix, vectors and its related operations



### Setup Steps:

In [63]:
#@title Please enter your registration id to start: { run: "auto", display-mode: "form" }
Id = "2418729" #@param {type:"string"}

In [54]:
#@title Please enter your password (normally your phone number) to continue: { run: "auto", display-mode: "form" }
password = "81548026" #@param {type:"string"}

In [64]:
#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython
import warnings
warnings.filterwarnings("ignore")

ipython = get_ipython()

notebook= "M1_AST_01_Linear_Algebra_A" #name of the notebook

def setup():
    from IPython.display import HTML, display
    display(HTML('<script src="https://dashboard.talentsprint.com/aiml/record_ip.html?traineeId={0}&recordId={1}"></script>'.format(getId(),submission_id)))
    print("Setup completed successfully")
    return

def submit_notebook():
    ipython.magic("notebook -e "+ notebook + ".ipynb")

    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword()}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:
        print(r["err"])
        return None
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None

    elif getAnswer1() and getAnswer2() and getComplexity() and getAdditional() and getConcepts() and getComments() and getMentorSupport():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional,
              "concepts" : Concepts, "record_id" : submission_id,
              "answer1" : Answer1, "answer2" : Answer2, "id" : Id, "file_hash" : file_hash,
              "notebook" : notebook,
              "feedback_experiments_input" : Comments,
              "feedback_mentor_support": Mentor_support}
      r = requests.post(url, data = data)
      r = json.loads(r.text)
      if "err" in r:
        print(r["err"])
        return None
      else:
        print("Your submission is successful.")
        print("Ref Id:", submission_id)
        print("Date of submission: ", r["date"])
        print("Time of submission: ", r["time"])
        print("View your submissions: https://learn-iisc.talentsprint.com/notebook_submissions")
        #print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
        return submission_id
    else: submission_id


def getAdditional():
  try:
    if not Additional:
      raise NameError
    else:
      return Additional
  except NameError:
    print ("Please answer Additional Question")
    return None

def getComplexity():
  try:
    if not Complexity:
      raise NameError
    else:
      return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None

def getConcepts():
  try:
    if not Concepts:
      raise NameError
    else:
      return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None


# def getWalkthrough():
#   try:
#     if not Walkthrough:
#       raise NameError
#     else:
#       return Walkthrough
#   except NameError:
#     print ("Please answer Walkthrough Question")
#     return None

def getComments():
  try:
    if not Comments:
      raise NameError
    else:
      return Comments
  except NameError:
    print ("Please answer Comments Question")
    return None


def getMentorSupport():
  try:
    if not Mentor_support:
      raise NameError
    else:
      return Mentor_support
  except NameError:
    print ("Please answer Mentor support Question")
    return None

def getAnswer1():
  try:
    if not Answer1:
      raise NameError
    else:
      return Answer1
  except NameError:
    print ("Please answer Question 1")
    return None

def getAnswer2():
  try:
    if not Answer2:
      raise NameError
    else:
      return Answer2
  except NameError:
    print ("Please answer Question 2")
    return None


def getId():
  try:
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup()
else:
  print ("Please complete Id and Password cells before running setup")



Setup completed successfully


### Importing required packages

In [108]:
import numpy as np
from math import *
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from numpy import linalg as la
from numpy.linalg import eig

### Types of Matrix

**Square Matrix**: In square matrix, the number of rows are equal to the number of columns.

1. Create a square matrix with elements 61 to 69.

In [82]:
# YOUR CODE HERE
elements = np.arange(61,70) # takes range from 61 to 69 and omits 70

size = int(np.ceil(np.sqrt(len(elements)))) #take the sqaure root of size of elements and ceil to next higher numner

squareMatrix = np.zeros((size, size), dtype=int) # create a square matrix with all zeros in the matrix
squareMatrix.flat[:len(elements)] = elements    # update the matrix with required range

print(squareMatrix)


[[61 62 63]
 [64 65 66]
 [67 68 69]]



**Upper Triangular Matrix**: It is a type of square matrix, where all the values below the main diagonal are 0.

**Lower Triangular Matrix**: It is a type of square matrix, where all the values above the main diagonal are 0.


2. Create an upper and lower triangular matrix of size 6x6 with random values.

In [83]:
matrix = np.random.rand(6,6)
print("Original Matrix:\n",matrix)

# Upper triangular matrix
# YOUR CODE HERE
upperTriangularMatrix  = np.triu(matrix) # triu give the required upper traiangular matrix with one line of code


# Lower triangular matrix
# YOUR CODE HERE

lowerTriangularMatrix = np.tril(matrix)
print(lowerTriangularMatrix)

Original Matrix:
 [[0.74296563 0.55829295 0.75611216 0.37985704 0.70841821 0.78944689]
 [0.80128044 0.16102261 0.59804636 0.78415996 0.36699471 0.79952808]
 [0.38424592 0.15369775 0.81635979 0.68619156 0.68413876 0.72521019]
 [0.8252165  0.87184634 0.49251305 0.53239298 0.44497369 0.751816  ]
 [0.66888886 0.67348646 0.05581293 0.95881867 0.76888982 0.31983479]
 [0.22614863 0.28783147 0.62458563 0.79842592 0.43007316 0.64748649]]
[[0.74296563 0.         0.         0.         0.         0.        ]
 [0.80128044 0.16102261 0.         0.         0.         0.        ]
 [0.38424592 0.15369775 0.81635979 0.         0.         0.        ]
 [0.8252165  0.87184634 0.49251305 0.53239298 0.         0.        ]
 [0.66888886 0.67348646 0.05581293 0.95881867 0.76888982 0.        ]
 [0.22614863 0.28783147 0.62458563 0.79842592 0.43007316 0.64748649]]


**Diagonal Matrix**: In a diagonal matrix, all the values are zero except the diagonal values

3. Create a diagonal matrix of size 3x3 with integer valules and do the following:

  i). Create a diagonal matrix with the values above the diagonal elements.
  
  ii). Create a diagonal matrix with the values below the diagonal elements.





In [84]:
M = np.array([np.arange(73,76),np.arange(32,35), np.arange(57,60)])
print("Matrix:\n",M)

# Diagonal Matrix
# YOUR CODE HERE

diagonalElements = np.diag(M) # Extracts the Diagonal elements from the matrix

diagonalMatrix = np.diag(diagonalElements) # creates a diagonal matrix swith given linear elements
print(diagonalMatrix)

# Using k=1 for getting the diagonal matrix with the values above the diagonal elements
# YOUR CODE HERE

upperDiagonalMatrix = np.diag(diagonalElements, k = 1) # creates upper diagonal matrix with K = 1 (above the diagobnal)
print(upperDiagonalMatrix)

# Using k=-1 for getting the diagonal matrix with the values below the diagonal elements
# YOUR CODE HERE
lowerDiagonalMatrix = np.diag(diagonalElements, k = -1) # creates upper diagonal matrix with K = 1 (below the diagobnal)
print(lowerDiagonalMatrix)

Matrix:
 [[73 74 75]
 [32 33 34]
 [57 58 59]]
[[73  0  0]
 [ 0 33  0]
 [ 0  0 59]]
[[ 0 73  0  0]
 [ 0  0 33  0]
 [ 0  0  0 59]
 [ 0  0  0  0]]
[[ 0  0  0  0]
 [73  0  0  0]
 [ 0 33  0  0]
 [ 0  0 59  0]]


Here all the non-diagonal elements are zero.

**Identity Matrix**: A matrix of size nxn where all diagonal values are 1 and other values are 0 is an identity matrix.

4. Create a 4x4 identity matrix with integer numbers.

In [85]:
# YOUR CODE HERE

identityMatrix = np.eye(4, dtype = int) # Identity matrix of size 4

print(identityMatrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


**Null Matrix**: A null matrix has all the values as zero.

5. Create a null matrix of integers with shape 6x6.

In [86]:
# YOUR CODE HERE
nullMatrix = np.zeros((6,6), dtype = int) #null matrix of size 6x6

print(nullMatrix)



[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


### Matrix Transpose, Inverse, and Determinant

**Transpose**: Transpose operation flips the matrix over its diagonal i.e. replacing rows with coloums and vice-versa.

1. Create a matrix and find its transpose.

In [87]:
# Creating a matrix
# YOUR CODE HERE
elements = np.arange(1,10)

size = int(np.ceil(np.sqrt(len(elements)))) #take the sqaure root of size of elements and ceil to next higher numner

squareMatrix = np.zeros((size, size), dtype=int) # create a square matrix with all zeros in the matrix
squareMatrix.flat[:len(elements)] = elements

# Matrix transpose
# YOUR CODE HERE
transposeMatrix = np.transpose(squareMatrix)
print(transposeMatrix)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


**Inverse**: This operation helps to create a matrix such that when it is multiplied by the original matrix, the result is an identity matrix.

2. Find the inverse of a matrix.

In [88]:
# Create a matrix
# YOUR CODE HERE
squareMatrix = np.random.randint(1, 10, size=(3, 3))

print(squareMatrix)
# Finding the inverse
# YOUR CODE HERE

determinent = np.linalg.det(squareMatrix) # get the determinent of the matrix

if determinent != 0:
   inverseMatrix = np.linalg.inv(squareMatrix)
   print(inverseMatrix)
else:
   print("Determinent is zero")


[[2 7 2]
 [5 1 4]
 [9 1 7]]
[[ 0.6 -9.4  5.2]
 [ 0.2 -0.8  0.4]
 [-0.8 12.2 -6.6]]


3. Create 3x3 matrix and find the inverse of it.

In [89]:
# Create a matrix
# YOUR CODE HERE
squareMatrix = np.random.randint(1, 10, size=(3, 3))

print(squareMatrix)

# Finding Inverse
# YOUR CODE HERE
determinent = np.linalg.det(squareMatrix) # get the determinent of the matrix

if determinent != 0:
   inverseMatrix = np.linalg.inv(squareMatrix)
   print(inverseMatrix)
else:
   print("Determinent is zero")

[[3 2 2]
 [3 1 7]
 [8 8 2]]
[[ 1.8        -0.4        -0.4       ]
 [-1.66666667  0.33333333  0.5       ]
 [-0.53333333  0.26666667  0.1       ]]


**Determinant**: Determinant of a matrix is a scalar value that helps to characterize the properties of a matrix.

4. Create a matrix of size 3x3 and find the determinant of it.

  To know more about Python libraries, click [here](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html)




In [90]:
# YOUR CODE HERE

squareMatrix = np.random.randint(1, 10, size=(3, 3))

print(squareMatrix)

determinent = np.linalg.det(squareMatrix) # get the determinent of the matrix

[[3 7 1]
 [3 8 3]
 [6 6 1]]


5. Create a 4x4 matrix and slice the rows and columns to get the middle sub-matrix and find its determinant.

In [109]:
# Create 4x4 matrix
# YOUR CODE HERE

squareMatrix = np.random.randint(1, 17, size=(4, 4))
print(squareMatrix)

# Slicing of rows and columns
# YOUR CODE HERE

middleSubMatrix = squareMatrix[1:3, 1:3]
print(middleSubMatrix)

# Finding the determinant
# YOUR CODE HERE

determinant = np.linalg.det(middleSubMatrix)
print(determinant)

[[16 12 15  7]
 [ 1  1  7 12]
 [10 16  3  6]
 [ 4 10  6 15]]
[[ 1  7]
 [16  3]]
-108.99999999999997



### Matrix Operations and Functions


### Addition

1. Create matrix and add a scalar to it.





In [110]:
# Create a matrix
# YOUR CODE HERE

squareMatrix = np.random.randint(1, 10, size=(3, 3))

print(squareMatrix)

scalar = 5 # scalar value of 5
# Scalar Addition
# YOUR CODE HERE

scalarAdditionMatrix = squareMatrix + scalar

print(scalarAdditionMatrix)


[[4 1 3]
 [7 5 2]
 [8 5 3]]
[[ 9  6  8]
 [12 10  7]
 [13 10  8]]


2. Create two matrices as matrix1 & matrix2. Then, perform addition operation on them.










In [93]:
# Creating matrices
# YOUR CODE HERE

squareMatrix1 = np.random.randint(1, 10, size=(3, 3))
print(squareMatrix1)

squareMatrix2 = np.random.randint(1, 10, size=(3, 3))
print(squareMatrix2)

# Matrix Addition
# YOUR CODE HERE

matrixAddition = squareMatrix1 + squareMatrix2

print(matrixAddition)

[[2 5 8]
 [4 3 2]
 [6 4 2]]
[[8 3 8]
 [2 9 5]
 [7 5 4]]
[[10  8 16]
 [ 6 12  7]
 [13  9  6]]


### Subtraction

3. Create a matrix of size 3x6 and subtract a scalar from it.



In [94]:
# Creating matrices
# YOUR CODE HERE

matrix = np.random.randint(1, 19, size=(3, 6))
print(matrix)

scalar = 5


# Scalar Substraction
# YOUR CODE HERE

matrixSubstraction = matrix - 5

print(matrixSubstraction)

[[ 3  1 14 17 14  9]
 [ 7 14 15  7  1 10]
 [ 9  1 15  9  7 18]]
[[-2 -4  9 12  9  4]
 [ 2  9 10  2 -4  5]
 [ 4 -4 10  4  2 13]]


4. Create two matrices of size 2x3 and subtract second matrix from the first one.

In [95]:
# Creating matrices
# YOUR CODE HERE

matrix = np.random.randint(1, 7, size=(2, 3))
print(matrix)

matrix1 = np.random.randint(1, 7, size=(2, 3))
print(matrix1)

# Matrix Subtraction
# YOUR CODE HERE

matrixSubstraction = matrix - matrix1

print(matrixSubstraction)

[[5 1 4]
 [6 4 2]]
[[5 6 3]
 [3 5 5]]
[[ 0 -5  1]
 [ 3 -1 -3]]


### Division

5. Create a 4x3 matrix and divide it by a scalar.






In [96]:
# Creating matrix
# YOUR CODE HERE

matrix = np.random.randint(1, 13, size=(4, 3))
print(matrix)

scalar = 5
# Scalar Division
# YOUR CODE HERE

matrixDivision=  matrix / 5
print(matrixDivision)

[[ 4  6  1]
 [ 5 11  2]
 [10  5  4]
 [12 12  3]]
[[0.8 1.2 0.2]
 [1.  2.2 0.4]
 [2.  1.  0.8]
 [2.4 2.4 0.6]]


6. Create two matrices and divide the first matrix by the second one.

In [97]:
# Creating matrices
# YOUR CODE HERE

squareMatrix1 = np.random.randint(1, 10, size=(3, 3))
print(squareMatrix1)

squareMatrix2 = np.random.randint(1, 10, size=(3, 3))
print(squareMatrix2)

# Matrix Division
# YOUR CODE HERE

matrixDivision=  squareMatrix1 / squareMatrix2
print(matrixDivision)

[[9 4 1]
 [3 7 2]
 [7 5 3]]
[[7 6 5]
 [5 4 5]
 [4 7 9]]
[[1.28571429 0.66666667 0.2       ]
 [0.6        1.75       0.4       ]
 [1.75       0.71428571 0.33333333]]


### Multiplication

7. Create a matrix and mulitply it by a Scalar.




In [98]:
# Creating matrix
# YOUR CODE HERE

squareMatrix = np.random.randint(1, 10, size=(3, 3))

print(squareMatrix)

scalar = 5 # scalar value of 5

# Scalar Product
# YOUR CODE HERE

scalarMultiply = squareMatrix * scalar

print(scalarMultiply)

[[9 8 2]
 [2 8 4]
 [9 4 6]]
[[45 40 10]
 [10 40 20]
 [45 20 30]]


Multiplication of two matrices is shown in the below diagram:



$A.B = \begin{bmatrix}
a & b\\
c & d\\
\end{bmatrix} \begin{bmatrix}
e & f\\
g & h\\
\end{bmatrix} = \begin{bmatrix}
ae+ bg & af+bh\\
ce+dg & cf+dh\\
\end{bmatrix}$

8. Create two matrices and multiply them.

  Note: Here, the corresponding elements are not multiplied. The multiplication rules are different from addition, subtraction, and division.

In [99]:
# Creating matrices
# YOUR CODE HERE
squareMatrix = np.random.randint(1, 10, size=(3, 3))
print(squareMatrix)

squareMatrix1 = np.random.randint(1, 10, size=(3, 3))
print(squareMatrix1)

# Dot Product
# YOUR CODE HERE

matrixMultiply = np.dot(squareMatrix, squareMatrix1)
print(matrixMultiply)

[[9 1 5]
 [5 8 3]
 [7 7 2]]
[[3 1 5]
 [6 8 8]
 [4 1 6]]
[[ 53  22  83]
 [ 75  72 107]
 [ 71  65 103]]


### Please answer the questions below to complete the experiment:




Consider the statements given below and answer Q1.


A. Every skew-symmetric matrix of odd order is non-singular

B. If determinant of a square matrix is non-zero, then it is non singular

C. Adjoint of symmetric matrix is symmetric

D. Adjoint of a diagonal matrix is diagonal

In [100]:
#@title Q.1. Which of the above statements is/are False?
Answer1 = "Only A" #@param ["","Only A","Both A & B","Only B", "Only C", "Only D", "Both B & C"]


Consider the matrix A and the values of a, b, and c given below for answering Q.2.

$A = \begin{bmatrix}
0 & 2b & c   \\
a & b & -c   \\
a & -b & c   \\
\end{bmatrix}$

<br>

A). a = $\pm \frac{1}{\sqrt{6}} $, b = $\pm \frac{1}{\sqrt{2}}$ , c = $\pm \frac{1}{\sqrt{2}} $


<br>

B). a = $\pm \frac{1}{\sqrt{6}} $, b = $\pm \frac{1}{\sqrt{3}}$ , c = $\pm \frac{1}{\sqrt{2}} $


<br>

C). a = $\pm \frac{1}{\sqrt{2}} $, b = $\pm \frac{1}{\sqrt{6}}$ , c = $\pm \frac{1}{\sqrt{3}} $

<br>

D). a = $\pm \frac{1}{\sqrt{2}} $, b = $\pm \frac{1}{\sqrt{2}}$ , c = $\pm \frac{1}{\sqrt{2}} $

In [111]:
#@title Q.2. If 'A' is an orthogonal matrix, then, what will be the values of a, b, and c.
Answer2 = "Only A" #@param ["","Only A","Only B","Only C","Only D", "None of the above"]


In [102]:
#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = "Good, But Not Challenging for me" #@param ["","Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging for me", "Was Tough, but I did it", "Too Difficult for me"]


In [ ]:
#@title If it was too easy, what more would you have liked to be added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = "it" #@param {type:"string"}


In [104]:
#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = "Yes" #@param ["","Yes", "No"]


In [105]:
#@title  Text and image description/explanation and code comments within the experiment: { run: "auto", vertical-output: true, display-mode: "form" }
Comments = "Very Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [106]:
#@title Mentor Support: { run: "auto", vertical-output: true, display-mode: "form" }
Mentor_support = "Very Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [112]:
#@title Run this cell to submit your notebook for grading { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id = return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")

Please answer Additional Question
